name: relocate-mug

task_name: relocate-mug

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    # image:
    #     shape: *image_shape
    #     type: rgb
    # point_cloud:
    #   shape: [512, 3]
    #   type: point_cloud
    shape: [39]
    type: low_dim
  action:
    shape: [30]

env_runner:
  _target_: diffusion_policy_3d.env_runner.video2dex_runner.Video2dexRunner
  eval_episodes: 20
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  task_name: relocate-mug
  render_size: 84
  use_point_crop: ${policy.use_point_crop}

dataset:
  _target_: diffusion_policy_3d.dataset.video2dex_dataset.VideoDataset
  zarr_path: data/demonstrations/relocate-mug.pkl
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
